version: "3.9"

services:
  flask-app:
    build: .
    container_name: expense-tracker
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: python app.py
